version: '2'
services:
  admin:
    image: nudj/admin:development
    environment:
      - NPM_TOKEN
    env_file: ../admin/.env
    volumes:
      - ../admin/.zshrc:/root/.zshrc
      - ../admin/src/app:/usr/src/app
      - ../admin/src/test:/usr/src/test
      - ../admin/src/.npmrc:/usr/src/.npmrc
      - ../admin/src/nodemon.json:/usr/src/nodemon.json
      - ../admin/src/package.json:/usr/src/package.json
      - ../admin/src/webpack.config.client.js:/usr/src/webpack.config.client.js
      - ../admin/src/webpack.config.dll.js:/usr/src/webpack.config.dll.js
      # yanks
      - ../framework/src:/usr/src/yank/@nudj/framework
      - ../library/src:/usr/src/yank/@nudj/library
      - ../components/src:/usr/src/yank/@nudj/components
      - ../api/src:/usr/src/yank/@nudj/api
    stdin_open: true
    command: /bin/zsh
